# Generated by Django 4.2.11 on 2024-03-06 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='department',
            new_name='dept',
        ),
    ]
